#!/usr/bin/env bash

if [ ! -f "DatabaseManager.java" ]; then
    echo "Error: cannot find the java class"
    exit 1
fi
if [ ! -f "Login.java" ]; then
    echo "Error: cannot find the java class"
    exit 1
fi
if [ ! -f "Trader.java" ]; then
    echo "Error: cannot find the java class"
    exit 1
fi
if [ ! -f "SellStock.java" ]; then
    echo "Error: cannot find the java class"
    exit 1
fi

echo "Compiling..."

javac Login.java
javac Manager.java
javac Register.java
javac Trader.java 
javac SellStock.java

java -cp /cs/class/cs174a/public/mysql-connector-java-5.1.44-bin.jar:. Login
