#!/usr/bin/env bash

if [ ! -f "DatabaseManager.java" ]; then
    echo "Error: cannot find the java class"
    exit 1
fi

if [ ! -f "DatabaseManager" ]; then
    echo "Compiling java file"
   javac DatabaseManager.java
fi

java -cp /cs/class/cs174a/public/mysql-connector-java-5.1.44-bin.jar:. DatabaseManager
